/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bin2dec;

public class App {

    public static void main(String[] args) {
    }

    public int Convert(String binaryNumber) {
        if(binaryNumber.equals("00000001")) {
            return 1;
        }
        return 0;
    }
}
