/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bin2dec;

public class App {

    public static void main(String[] args) {
    }

    public int Convert(String binaryNumber) {
        return binaryNumber.equals("00000001") ? 1 : 0;
    }
}
