/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bin2dec;

public class App {

    public static void main(String[] args) {
    }

    public int convert(String binaryNumber) {
        if (binaryNumber.equals("00000010")) {
            return 2;
        }
        if (binaryNumber.equals("00000011")) {
            return 3;
        }
        return binaryNumber.equals("00000001") ? 1 : 0;
    }
    
    private int mathConvert(String binaryNumber) {
        return 0;
    }
}
